Dit is een handleiding voor het gebruik van GPG encryptie.
GPG encryptie kan worden gebruikt voor het versleutelen, signeren en authenticatie.
Gebruikelijk is om dergelijke sleutels op te slaan op de harddisk van een computer.
In deze handleiding keizen wij ervoor om de prive sleutel op te slaan op een fysieke sleutel specifiek een link:https://www.yubico.com/products/[YubiKey] .

Sleutels opgelagen op een Yubikey kunnen niet geexfilteerd worden in tegenstelling tot sleutels die worden op geslagen op een harddisk.
Verder heeft een fysieke sleutel als voordeel dat hij op meerderde computers gebruikt kan worden, hetgeen het dagelijks gebruik vereenvoudigd.
Een hardware sleutelkan ook gebruikt worden om in te loggen op servers middels SSH/GPG, in plaats van een lang wachtwoord kan de sleutel ontgrendeld worden met een pincode. 
Alle cryptografische handelingen worden op de sleutel uitgevoerd, in plaats van in geheugen van een computer.

# Voorbereiding

Er zijn verschillende veel manieren om sleutels te genereren. Belanrijk is om er zeker van te zijn dat een derde niet bij de sleutels kan komen.
UIteindelijk is het dreigingsniveau dat iemand heeft bepalend voor welke installatie wijze als veilig wordt verondersteld.
Hieronder een rangschikking van omgevingen van minst veilig naar meest veilig.

1. de dagelijks ingebruik zijnde computer
2. een virtuele machine op de dagelijk in gebruik zijnde computer
3. een geharde Linux of BSD installatie
4. Live images zoals Debian Live of Tails
5. Computer zonder Intel ME
6. Een computer die niet is aangesloten op een netwek (air-gapped)


Afhankelijk van iemands dreigingsvctor (threat vector) is het bllanrijk te weten dat 

Voor deze handleiding is gebruik gemaakt van een PC Engines APU die niet verbonden is met een netwerk.
De computer wordt voorzien van een schone Debian installatie.

Debian kan op de volgende manier worden verkregen:

[,console]
----
$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/SHA512SUMS

$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/SHA512SUMS.sign

$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/$(awk '/xfce.iso/ {print $2}' SHA512SUMS)
----

Controleer de handtekening en de bestand hashes met behulp van GPG:

[,console]
----
$ gpg --verify SHA512SUMS.sign SHA512SUMS
gpg: Signature made Sat 09 May 2020 05:17:57 PM PDT
gpg:                using RSA key DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: Can't check signature: No public key

$ gpg --keyserver hkps://keyring.debian.org --recv DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: key 0xDA87E80D6294BE9B: public key "Debian CD signing key <debian-cd@lists.debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1

$ gpg --verify SHA512SUMS.sign SHA512SUMS
gpg: Signature made Sat 09 May 2020 05:17:57 PM PDT
gpg:                using RSA key DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: Good signature from "Debian CD signing key <debian-cd@lists.debian.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: DF9B 9C49 EAA9 2984 3258  9D76 DA87 E80D 6294 BE9B
----

Controleer of de SHA512 hash overeenkomt met de hash in gesigneerde bestand.

[,console]
----
$ grep $(sha512sum debian-live-*-amd64-xfce.iso) SHA512SUMS
SHA512SUMS:799ec1fdb098caa7b60b71ed1fdb1f6390a1c6717b4314265e7042fa271c84f67fff0d0380297f60c4bcd0c1001e08623ab3d2a2ad64079d83d1795c40eb7a0a  debian-live-10.5.0-amd64-xfce.iso
----

Pak een USB stick en kopieer het gedownloade iso-bestand erop.

[,console]
----
$ sudo dmesg | tail
usb-storage 3-2:1.0: USB Mass Storage device detected
scsi host2: usb-storage 3-2:1.0
scsi 2:0:0:0: Direct-Access     TS-RDF5  SD  Transcend    TS3A PQ: 0 ANSI: 6
sd 2:0:0:0: Attached scsi generic sg1 type 0
sd 2:0:0:0: [sdb] 31116288 512-byte logical blocks: (15.9 GB/14.8 GiB)
sd 2:0:0:0: [sdb] Write Protect is off
sd 2:0:0:0: [sdb] Mode Sense: 23 00 00 00
sd 2:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
sdb: sdb1 sdb2
sd 2:0:0:0: [sdb] Attached SCSI removable disk

$ sudo dd if=debian-live-10.4.0-amd64-xfce.iso of=/dev/sdb bs=4M; sync
465+1 records in
465+1 records out
1951432704 bytes (2.0 GB, 1.8 GiB) copied, 42.8543 s, 45.5 MB/s
----

Sluit de computer af en start hem opnieuw op met de live versie van Debian.

# Benodigde software

[,console]
----
$ sudo apt update && sudo apt -y upgrade

$ sudo apt -y install wget gnupg2 gnupg-agent dirmngr cryptsetup scdaemon pcscd secure-delete hopenpgp-tools yubikey-personalization
----


[,console]
----
$ sudo apt -y install python3-pip python3-pyscard

$ pip3 install PyOpenSSL

$ pip3 install yubikey-manager

$ sudo service pcscd start

$ ~/.local/bin/ykman openpgp info
----


# Entropy

Voor het genereren van cryptographische sleutels is veel randomness nodig.

Op Linux systemen kan dat op de volgende manier worden gecontroleerd.

[,console]
----
$ cat /proc/sys/kernel/random/entropy_avail
265
----

De meeste besturingssystemen gebruiken op software gebaseerde generatoren voor pseudowillekeurige getallen. 
Op nieuwere machines zijn er op CPU gebaseerde hardware random number generators (HRNG) of u kunt een apart
hardwareapparaat gebruiken zoals de White Noise of link:https://onerng.info/onerng/[OneRNG] om de snelheid
van het genereren van entropie en mogelijk de kwaliteit te verhogen.

# OneRNG

Installeer rng-tools software:

[,console]
----
$ sudo apt -y install at rng-tools python3-gnupg openssl
----

Voorbeeld OneNRG

[,console]
----
$ wget https://github.com/OneRNG/onerng.github.io/raw/master/sw/onerng_3.7-1_all.deb

$ sha256sum onerng_3.7-1_all.deb
b7cda2fe07dce219a95dfeabeb5ee0f662f64ba1474f6b9dddacc3e8734d8f57  onerng_3.7-1_all.deb

$ sudo dpkg -i onerng_3.7-1_all.deb

$ echo "HRNGDEVICE=/dev/ttyACM0" | sudo tee /etc/default/rng-tools
----

Plug het apperaat in en restart rng-tools:

[,console]
----
$ sudo atd

$ sudo service rng-tools restart
----

link:https://onerng.info/onerng/[OneRNG]

----
The linux kernel has changed the way that it supports RNG devices - it no longer correctly supports the entropy driven API for providing data to the kernel entropy pool - we have changed the OneRNG daemon script to periodicaly feed the kernel with new entropy, you can change this rate by editing the OneRNG config file /etc/onerng.conf, then removing the OneRNG and plugging it back in again

Starting with version 3.7 you can verify that your OneRNG is working correctly by noting that the orange LED blinks every second or so.

----








[,console]
----

----

[,console]
----

----

[,console]
----

----

[,console]
----

----

[,console]
----

----

[,console]
----

----

[,console]
----

----

[,console]
----

----































