Dit is een handleiding voor het gebruik van GPG encryptie.
GPG encryptie kan worden gebruikt voor het versleutelen, signeren en authenticatie.
Gebruikelijk is om dergelijke sleutels op te slaan op de harddisk van een computer.
In deze handleiding keizen wij ervoor om de prive sleutel op te slaan op een fysieke sleutel specifiek een link:https://www.yubico.com/products/[YubiKey] .

Sleutels opgelagen op een Yubikey kunnen niet geexfilteerd worden in tegenstelling tot sleutels die worden op geslagen op een harddisk.
Verder heeft een fysieke sleutel als voordeel dat hij op meerderde computers gebruikt kan worden, hetgeen het dagelijks gebruik vereenvoudigd.
Een hardware sleutelkan ook gebruikt worden om in te loggen op servers middels SSH/GPG, in plaats van een lang wachtwoord kan de sleutel ontgrendeld worden met een pincode. 
Alle cryptografische handelingen worden op de sleutel uitgevoerd, in plaats van in geheugen van een computer.

# Voorbereiding

Er zijn verschillende veel manieren om sleutels te genereren. Belanrijk is om er zeker van te zijn dat een derde niet bij de sleutels kan komen.
UIteindelijk is het dreigingsniveau dat iemand heeft bepalend voor welke installatie wijze als veilig wordt verondersteld.
Hieronder een rangschikking van omgevingen van minst veilig naar meest veilig.

1. de dagelijks ingebruik zijnde computer
2. een virtuele machine op de dagelijk in gebruik zijnde computer
3. een geharde Linux of BSD installatie
4. Live images zoals Debian Live of Tails
5. Computer zonder Intel ME
6. Een computer die niet is aangesloten op een netwek (air-gapped)


Afhankelijk van iemands dreigingsvctor (threat vector) is het bllanrijk te weten dat 

Voor deze handleiding is gebruik gemaakt van een PC Engines APU die niet verbonden is met een netwerk.
De computer wordt voorzien van een schone Debian installatie.

Debian kan op de volgende manier worden verkregen:

[,console]
----
$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/SHA512SUMS

$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/SHA512SUMS.sign

$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/$(awk '/xfce.iso/ {print $2}' SHA512SUMS)
----

Controleer de handtekening en de bestand hashes met behulp van GPG:

[,console]
----
$ gpg --verify SHA512SUMS.sign SHA512SUMS
gpg: Signature made Sat 09 May 2020 05:17:57 PM PDT
gpg:                using RSA key DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: Can't check signature: No public key

$ gpg --keyserver hkps://keyring.debian.org --recv DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: key 0xDA87E80D6294BE9B: public key "Debian CD signing key <debian-cd@lists.debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1

$ gpg --verify SHA512SUMS.sign SHA512SUMS
gpg: Signature made Sat 09 May 2020 05:17:57 PM PDT
gpg:                using RSA key DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: Good signature from "Debian CD signing key <debian-cd@lists.debian.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: DF9B 9C49 EAA9 2984 3258  9D76 DA87 E80D 6294 BE9B
----




