Dit is een handleiding voor het gebruik van GPG encryptie.
GPG encryptie kan worden gebruikt voor het versleutelen, signeren en authenticatie.
Gebruikelijk is om dergelijke sleutels op te slaan op de harddisk van een computer.
In deze handleiding keizen wij ervoor om de prive sleutel op te slaan op een fysieke sleutel specifiek een link:https://www.yubico.com/products/[YubiKey] .

Sleutels opgelagen op een Yubikey kunnen niet geexfilteerd worden in tegenstelling tot sleutels die worden op geslagen op een harddisk.
Verder heeft een fysieke sleutel als voordeel dat hij op meerderde computers gebruikt kan worden, hetgeen het dagelijks gebruik vereenvoudigd.
Een hardware sleutelkan ook gebruikt worden om in te loggen op servers middels SSH/GPG, in plaats van een lang wachtwoord kan de sleutel ontgrendeld worden met een pincode. 
Alle cryptografische handelingen worden op de sleutel uitgevoerd, in plaats van in geheugen van een computer.

# Voorbereiding

Er zijn verschillende veel manieren om sleutels te genereren. Belanrijk is om er zeker van te zijn dat een derde niet bij de sleutels kan komen.
UIteindelijk is het dreigingsniveau dat iemand heeft bepalend voor welke installatie wijze als veilig wordt verondersteld.
Hieronder een rangschikking van omgevingen van minst veilig naar meest veilig.

1. de dagelijks ingebruik zijnde computer
2. een virtuele machine op de dagelijk in gebruik zijnde computer
3. een geharde Linux of BSD installatie
4. Live images zoals Debian Live of Tails
5. Computer zonder Intel ME
6. Een computer die niet is aangesloten op een netwek (air-gapped)


Afhankelijk van iemands dreigingsvctor (threat vector) is het bllanrijk te weten dat 

Voor deze handleiding is gebruik gemaakt van een PC Engines APU die niet verbonden is met een netwerk.
De computer wordt voorzien van een schone Debian installatie.

Debian kan op de volgende manier worden verkregen:

[,console]
----
$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/SHA512SUMS

$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/SHA512SUMS.sign

$ curl -LfO https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/$(awk '/xfce.iso/ {print $2}' SHA512SUMS)
----

Controleer de handtekening en de bestand hashes met behulp van GPG:

[,console]
----
$ gpg --verify SHA512SUMS.sign SHA512SUMS
gpg: Signature made Sat 09 May 2020 05:17:57 PM PDT
gpg:                using RSA key DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: Can't check signature: No public key

$ gpg --keyserver hkps://keyring.debian.org --recv DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: key 0xDA87E80D6294BE9B: public key "Debian CD signing key <debian-cd@lists.debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1

$ gpg --verify SHA512SUMS.sign SHA512SUMS
gpg: Signature made Sat 09 May 2020 05:17:57 PM PDT
gpg:                using RSA key DF9B9C49EAA9298432589D76DA87E80D6294BE9B
gpg: Good signature from "Debian CD signing key <debian-cd@lists.debian.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: DF9B 9C49 EAA9 2984 3258  9D76 DA87 E80D 6294 BE9B
----

Controleer of de SHA512 hash overeenkomt met de hash in gesigneerde bestand.

[,console]
----
$ grep $(sha512sum debian-live-*-amd64-xfce.iso) SHA512SUMS
SHA512SUMS:799ec1fdb098caa7b60b71ed1fdb1f6390a1c6717b4314265e7042fa271c84f67fff0d0380297f60c4bcd0c1001e08623ab3d2a2ad64079d83d1795c40eb7a0a  debian-live-10.5.0-amd64-xfce.iso
----

Pak een USB stick en kopieer het gedownloade iso-bestand erop.

[,console]
----
$ sudo dmesg | tail
usb-storage 3-2:1.0: USB Mass Storage device detected
scsi host2: usb-storage 3-2:1.0
scsi 2:0:0:0: Direct-Access     TS-RDF5  SD  Transcend    TS3A PQ: 0 ANSI: 6
sd 2:0:0:0: Attached scsi generic sg1 type 0
sd 2:0:0:0: [sdb] 31116288 512-byte logical blocks: (15.9 GB/14.8 GiB)
sd 2:0:0:0: [sdb] Write Protect is off
sd 2:0:0:0: [sdb] Mode Sense: 23 00 00 00
sd 2:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
sdb: sdb1 sdb2
sd 2:0:0:0: [sdb] Attached SCSI removable disk

$ sudo dd if=debian-live-10.4.0-amd64-xfce.iso of=/dev/sdb bs=4M; sync
465+1 records in
465+1 records out
1951432704 bytes (2.0 GB, 1.8 GiB) copied, 42.8543 s, 45.5 MB/s
----

Sluit de computer af en start hem opnieuw op met de live versie van Debian.

# Benodigde software

[,console]
----
$ sudo apt update && sudo apt -y upgrade

$ sudo apt -y install wget gnupg2 gnupg-agent dirmngr cryptsetup scdaemon pcscd secure-delete hopenpgp-tools yubikey-personalization
----


[,console]
----
$ sudo apt -y install python3-pip python3-pyscard

$ pip3 install PyOpenSSL

$ pip3 install yubikey-manager

$ sudo service pcscd start

$ ~/.local/bin/ykman openpgp info
----


# Entropy

Voor het genereren van cryptographische sleutels is veel randomness nodig.

Op Linux systemen kan dat op de volgende manier worden gecontroleerd.

[,console]
----
$ cat /proc/sys/kernel/random/entropy_avail
265
----

De meeste besturingssystemen gebruiken op software gebaseerde generatoren voor pseudowillekeurige getallen. 
Op nieuwere machines zijn er op CPU gebaseerde hardware random number generators (HRNG) of u kunt een apart
hardwareapparaat gebruiken zoals de White Noise of link:https://onerng.info/onerng/[OneRNG] om de snelheid
van het genereren van entropie en mogelijk de kwaliteit te verhogen.

# OneRNG

Installeer rng-tools software:

[,console]
----
$ sudo apt -y install at rng-tools python3-gnupg openssl
----

Voorbeeld OneNRG

[,console]
----
$ wget https://github.com/OneRNG/onerng.github.io/raw/master/sw/onerng_3.7-1_all.deb

$ sha256sum onerng_3.7-1_all.deb
b7cda2fe07dce219a95dfeabeb5ee0f662f64ba1474f6b9dddacc3e8734d8f57  onerng_3.7-1_all.deb

$ sudo dpkg -i onerng_3.7-1_all.deb

$ echo "HRNGDEVICE=/dev/ttyACM0" | sudo tee /etc/default/rng-tools
----

Plug het apperaat in en restart rng-tools:

[,console]
----
$ sudo atd

$ sudo service rng-tools restart
----

link:https://onerng.info/onerng/[OneRNG]

Release 3.7 is a maintenance release, if your OneRNG is working well for you there is no reason to upgrade the software. 
There are two main changes, both in response to changes in modern linux systems:

We now use python3 for verifying the cryptographic signature of the device's firmware
The linux kernel has changed the way that it supports RNG devices - it no longer correctly supports the entropy driven API for providing data to the kernel entropy pool - we have changed the OneRNG daemon script to periodicaly feed the kernel with new entropy, you can change this rate by editing the OneRNG config file /etc/onerng.conf, then removing the OneRNG and plugging it back in again
Starting with version 3.7 you can verify that your OneRNG is working correctly by noting that the orange LED blinks every second or so.


# Sleutels genereren

## Tijdelijke werkfolder 

[,console]
----
$ export GNUPGHOME=$(mktemp -d -t gnupg_$(date +%Y%m%d%H%M)_XXX)
----

## Geharde configuratie maken

[,console]
----
$ wget -O $GNUPGHOME/gpg.conf 

$ grep -ve "^#" $GNUPGHOME/gpg.conf
personal-cipher-preferences AES256 AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256
personal-compress-preferences ZLIB BZIP2 ZIP Uncompressed
default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
cert-digest-algo SHA512
s2k-digest-algo SHA512
s2k-cipher-algo AES256
charset utf-8
fixed-list-mode
no-comments
no-emit-version
keyid-format 0xlong
list-options show-uid-validity
verify-options show-uid-validity
with-fingerprint
require-cross-certification
no-symkey-cache
use-agent
throw-keyids
----

Sluit alle netwerkverbindingen af tijdens het maken van de sleutels. 

# Master Sleutel

De eerste sleutel die moet worden gegenereerd, is de hoofdsleutel. 
Deze wordt alleen gebruikt voor certificering: om subsleutels uit te geven die worden gebruikt voor codering, ondertekening en authenticatie.

De hoofdsleutel moet te allen tijde offline blijven en alleen toegankelijk zijn om subsleutels in te trekken of uit te geven.
Sleutels kunnen ook op de YubiKey zelf worden gegenereerd om ervoor te zorgen dat er geen andere kopieën bestaan.

U wordt gevraagd een wachtwoordzin in te voeren en te verifiëren. Houd deze bij de hand, want u hebt deze later meerdere keren nodig.

Genereer een sterke wachtwoordzin die op een veilige plaats kan worden bewaard of onthouden:

[,console]
----
$ gpg --gen-random --armor 0 24
2IUW55aTFzvSOmg7/Z4Uz+GWAmes0xTm
----

De master sleutel krijg geen expiratie datum

[,console]
----
$ gpg --expert --full-generate-key
Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
   (7) DSA (set your own capabilities)
   (8) RSA (set your own capabilities)
   (9) ECC and ECC
  (10) ECC (sign only)
  (11) ECC (set your own capabilities)
  (13) Existing key
  (14) Existing key from card
Your selection? 8

Possible actions for a RSA key: Sign Certify Encrypt Authenticate 
Current allowed actions: Sign Certify Encrypt 

   (S) Toggle the sign capability
   (E) Toggle the encrypt capability
   (A) Toggle the authenticate capability
   (Q) Finished

Your selection? E

Possible actions for a RSA key: Sign Certify Encrypt Authenticate 
Current allowed actions: Sign Certify 

   (S) Toggle the sign capability
   (E) Toggle the encrypt capability
   (A) Toggle the authenticate capability
   (Q) Finished

Your selection? S

Possible actions for a RSA key: Sign Certify Encrypt Authenticate 
Current allowed actions: Certify 

   (S) Toggle the sign capability
   (E) Toggle the encrypt capability
   (A) Toggle the authenticate capability
   (Q) Finished

Your selection? Q
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (3072) 4096
Requested keysize is 4096 bits
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0) 0
Key does not expire at all
Is this correct? (y/N) y
----

Voer je naam en e-mailadres in:

[,console]
----
GnuPG needs to construct a user ID to identify your key.

Real name: Peter Vissers
Email address: tj@gmail.com
Comment: 
You selected this USER-ID:
    "Terminal Junkie <tj@gmail.com>"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? o
We need to generate a lot of random bytes. It is a good idea to perform
some other action (type on the keyboard, move the mouse, utilize the
disks) during the prime generation; this gives the random number
generator a better chance to gain enough entropy.
gpg: /tmp/gnupg_202210290110_LWZ/trustdb.gpg: trustdb created
gpg: key 0x9B0D301A133E5D74 marked as ultimately trusted
gpg: directory '/tmp/gnupg_202210290110_LWZ/openpgp-revocs.d' created
gpg: revocation certificate stored as '/tmp/gnupg_202210290110_LWZ/openpgp-revocs.d/3E8B1C7D728F074719DB29009B0D301A133E5D74.rev'
public and secret key created and signed.

pub   rsa4096/0x9B0D301A133E5D74 2022-10-28 [C]
      Key fingerprint = 3E8B 1C7D 728F 0747 19DB  2900 9B0D 301A 133E 5D74
uid                              Terminal Junkie <tj@gmail.com>
----

Exporteer de sleutel als variabele voor later gebruik.

[,console]
----
$ export KEYID=0x9B0D301A133E5D74
----

# Sub-sleutels


[,console]
----
$ gpg --expert --edit-key $KEYID
Secret key is available.

gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
sec  rsa4096/0x9B0D301A133E5D74
     created: 2022-10-28  expires: never       usage: C   
     trust: ultimate      validity: ultimate
[ultimate] (1). Terminal Junkie <tj@gmail.com>

----

[,console]
----

----































